### ISSUE TITLE
README.md: explain why is fast ?

### ISSUE THREAD

**Issue by franck34** [kalm/kalm.js#16]
Hi frederic !

Should be great if you explain quickly why kalm is fast ? (in the README)

Thank you

**Comment by fed135** [comment]
Thanks for the comment! I touch a bit on what it does in the wiki (https://github.com/kalm/kalm.js/wiki) but it definitely wouldn't hurt to add a bit the README.

**Comment by franck34** [comment]
Cool, thank you.

I don't see any C library, that's why i'm surprised. Wondering what's the magic behind, i don't see any notable code regarding perf, except some parts are in typescript rather thanjs perhaps ?

Do you plan to add zlib compression ? not sure it's revelant here.

I'll probably implement/test/bench your lib in a jsonrpc over tcp context (see https://github.com/sloki-project/)

Thank you for publishing kalm !

**Comment by fed135** [comment]
Ça fait plaisir :)

To give you a quick summary, the performance gain comes from buffering packets before sending them- eventually sending batches instead of individual packages. You'll start seeing gains the more traffic you process. This is because the net stack is relatively slow. You can read more about the algorithm [here](https://en.wikipedia.org/wiki/Nagle%27s_algorithm)

Kalm was designed to perform that function (often found in online game servers) while allowing you to instrument around it easily. 

For example, to add zlib (or preferably some other compression protocol like [snappy](https://github.com/zhipeng-jia/snappyjs)) you can compress it before passing it to kalm and specify `json: false` in the options.
